services:
  frontend:
    image: aman-devops-web:1.0
    container_name: aman-frontend
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - aman-network

  backend:
    build:
      context: ./backend
    container_name: aman-backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - aman-network

  database:
    image: mysql:8.0
    container_name: aman-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devopsdb
      MYSQL_USER: aman
      MYSQL_PASSWORD: amanpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - aman-network

volumes:
  mysql-data:

networks:
  aman-network:
    driver: bridge
