services:
  web:
    image: aman-devops-web:1.0
    container_name: aman-compose-web
    ports:
      - "8083:80"
    networks:
      - aman-compose-network

  redis:
    image: redis:latest
    container_name: aman-compose-redis
    networks:
      - aman-compose-network

networks:
  aman-compose-network:
    driver: bridge
